require recipes-kernel/linux/linux.inc

SECTION = "kernel"

# Mark archs/machines that this kernel supports
COMPATIBLE_MACHINE = "athene"

DESCRIPTION = "Linux kernel for the Motorola G4 device based on the official \
source from Motorola"

ANDROID_BOOTIMG_CMDLINE = "console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci lpm_levels.sleep_disabled=1 earlyprintk"
ANDROID_BOOTIMG_KERNEL_RAM_BASE = "0x80008000"
ANDROID_BOOTIMG_RAMDISK_RAM_BASE = "0x81000000"
ANDROID_BOOTIMG_SECOND_RAM_BASE = "0x80f00000"
ANDROID_BOOTIMG_TAGS_RAM_BASE = "0x80000100"

inherit kernel_android

# kernel.bbclass sets S = "${STAGING_KERNEL_DIR}", and do_symlink_kernsrc only
# moves the unpacked tree there when the recipe points S somewhere else.
S = "${UNPACKDIR}/${BP}"

SRC_URI = "git://github.com/shr-distribution/linux.git;branch=athene/3.10/cm-14.1;protocol=https"

do_configure:prepend() {
    cp -v -f ${S}/arch/arm/configs/athene_defconfig ${WORKDIR}/defconfig
}

SRCREV = "f8406b96363849c38204def56dfe7f10bc42c567"

LINUX_VERSION = "3.10.107"
PV = "${LINUX_VERSION}+git"
# for bumping PR bump MACHINE_KERNEL_PR in the machine config
inherit machine_kernel_pr

do_install:append () {
    # make headers_install leaves kbuild's ..install.cmd bookkeeping behind, and
    # linux.inc ships everything under ${exec_prefix}/src/linux* as kernel-headers.
    # Those files record absolute command lines, which wrynose rejects as
    # "contains reference to TMPDIR [buildpaths]".
    find ${D}${exec_prefix}/src -name '..install.cmd' -delete 2>/dev/null || true
    rm -rf ${D}/usr/src/usr

}

# lib/oid_registry_data.c and drivers/tty/vt/consolemap_deftbl.c are generated by
# host tools that write their own path into the output, and they land in the -src
# package. That is build metadata inside debug sources, not anything the kernel
# ships; silencing it beats patching the kernel's generators to prefix-map argv.
INSANE_SKIP:${PN}-src += "buildpaths"
