require recipes-kernel/linux/linux.inc
# Options every Halium target needs; see the file for what and why.
require recipes-kernel/linux/halium-kernel.inc
# Binder nodes, veth, overlayfs and the rest of what Waydroid needs.
require recipes-kernel/linux/waydroid-kernel.inc

SECTION = "kernel"

# Mark archs/machines that this kernel supports
COMPATIBLE_MACHINE = "^athena$"

DESCRIPTION = "Linux kernel for the BlackBerry KEY2 (athena, SDM660), based on \
tim-ecoder's 4.19 port of the BlackBerry/CAF sources used by LineageOS 23.2"

# VERIFIED against the shipping e-4.1.1-a15-20260725 athena boot.img, not just
# read out of the BoardConfig: header v0, 4096 byte pages, kernel 0x00008000,
# ramdisk 0x01000000, tags 0x00000100, second 0x00000000 (no second image).
# BOARD_KERNEL_BASE is 0x00000000 with the standard 0x8000 kernel offset, which
# is why the kernel address looks unusually low; sargo uses the same set.
#
# The cmdline is that image's, verbatim, plus androidboot.selinux=permissive.
# It differs slightly from the lineage-23.2 BoardConfig (which has
# regulator_ignore_unused and lacks swiotlb=1 / androidboot.serialconsole=0);
# the shipping image wins because it is what this bootloader has actually
# booted.
ANDROID_BOOTIMG_CMDLINE = "androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 androidboot.configfs=true androidboot.usbcontroller=a800000.dwc3 coherent_pool=1280K androidboot.serialconsole=0 androidboot.selinux=permissive"
ANDROID_BOOTIMG_HEADER_VERSION = "0"
ANDROID_BOOTIMG_PAGESIZE = "4096"
# ANDROID_BOOTIMG_PAGESIZE above is only read by android_bootimg_v2() in
# kernel_android.bbclass. athena is header v0, and the v0 path drives abootimg,
# which ignores that variable and defaults to 2048 byte pages - so it has to be
# passed through by hand or aboot gets an image whose sections are at the wrong
# offsets. athena is the first v0 + 4096 device here: every other v0 machine
# (tissot, mido, rosy, ...) is 2048, and sargo is 4096 but header v2, where the
# python writer honours the variable directly.
#
# Verified that abootimg does accept it: -c pagesize=4096 yields a v0 header
# with page_size=4096 and the offsets below intact.
ANDROID_BOOTIMG_EXTRA_ABOOTIMG_ARGS = "-c pagesize=4096"
ANDROID_BOOTIMG_KERNEL_RAM_BASE = "0x00008000"
ANDROID_BOOTIMG_RAMDISK_RAM_BASE = "0x01000000"
ANDROID_BOOTIMG_SECOND_RAM_BASE = "0x00000000"
ANDROID_BOOTIMG_TAGS_RAM_BASE = "0x00000100"

# 4.19 replaced the plain GPLv2 text in COPYING with the SPDX preamble
# ("The Linux Kernel is provided under: SPDX-License-Identifier: GPL-2.0 WITH
# Linux-syscall-note"), so the checksum linux.inc carries for the 4.9/4.14
# trees does not match and do_populate_lic fails as a QA error.
LIC_FILES_CHKSUM = "file://COPYING;md5=bbea815ee2795b2f4230826c0c6b8814"

inherit kernel_android pkgconfig

# kernel.bbclass sets S = "${STAGING_KERNEL_DIR}", and do_symlink_kernsrc only
# moves the unpacked tree there when the recipe points S somewhere else.
S = "${UNPACKDIR}/${BP}"

SRC_URI = "git://github.com/shr-distribution/linux.git;branch=key2/${LINUX_VERSION};protocol=https \
           file://luneos.cfg \
"

FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"
# shr-distribution/linux key2/4.19:
# "kbuild: demote two more GCC 15 warning classes for the qcacld module build"
SRCREV = "e215d6f6ff3dfacdb1ddcc502c9f4d27ae110923"

LINUX_VERSION = "4.19"
KV = "4.19.325"
PV = "${KV}+git"
# for bumping PR bump MACHINE_KERNEL_PR in the machine config
inherit machine_kernel_pr

DEPENDS += "dtc-native openssl-native"

# athena-perf_defconfig is the config the LineageOS device tree selects
# (TARGET_KERNEL_CONFIG in device/blackberry/athena/BoardConfig.mk). luneos.cfg
# is the LuneOS/Halium delta on top of it; later lines win over earlier ones
# when kconfig reads the concatenation.
#
# Verified with mer_verify_kernel_config: the stock defconfig scores 8 errors /
# 54 warnings, with the fragment 1 error (CONFIG_DUMMY, deliberate - see the
# fragment) / 37 warnings, all of them optional items.
do_configure:prepend() {
    cat ${S}/arch/arm64/configs/athena-perf_defconfig ${UNPACKDIR}/luneos.cfg > ${WORKDIR}/defconfig
}

# Three files kbuild generates into ${B} record the absolute path of the tool
# or input they were made from, in a banner comment:
#
#   drivers/tty/vt/consolemap_deftbl.c    "conmakehash <abs>/drivers/tty/vt/cp437.uni"
#   drivers/video/logo/logo_linux_clut224.c  "generated from <abs>/...logo_linux_clut224.ppm"
#   lib/oid_registry_data.c               "Automatically generated by <abs>/lib/build_OID_registry"
#
# linux.inc ships the build tree as the -src package, so those paths go out with
# it and wrynose fails do_package_qa with "contains reference to TMPDIR
# [buildpaths]". Rewrite the banners to name the files the way an in-tree build
# would; they are comments, and the generated data below them is unchanged.
# Same treatment as mindphone's arch/arm/tools/gen-mach-types banner.
do_compile:append() {
    for f in drivers/tty/vt/consolemap_deftbl.c \
             drivers/video/logo/logo_linux_clut224.c \
             lib/oid_registry_data.c; do
        if [ -f ${B}/$f ]; then
            sed -i -e "s|${STAGING_KERNEL_DIR}/||g" -e "s|${B}/||g" ${B}/$f
        fi
    done
}

do_install:append () {
    # make headers_install leaves kbuild's ..install.cmd bookkeeping behind, and
    # linux.inc ships everything under ${exec_prefix}/src/linux* as kernel-headers.
    # Those files record absolute command lines, which wrynose rejects as
    # "contains reference to TMPDIR [buildpaths]".
    find ${D}${exec_prefix}/src -name '..install.cmd' -delete 2>/dev/null || true
    rm -rf ${D}/usr/src/usr
}

# scripts/unifdef.c declares "static bool constexpr;" and assigns to it. C23
# made constexpr a keyword and the host GCC here defaults to -std=gnu23, so
# building the kernel host tools (unifdef is pulled in by headers_install)
# fails:
#
#   scripts/unifdef.c:206:1: error: 'constexpr' in empty declaration
#
# Upstream renamed the variable in 6.7; this kernel predates that. Only the
# host tools are affected - the kernel itself is built with OE's cross
# toolchain - and kernel.bbclass passes HOSTCFLAGS="${BUILD_CFLAGS}", so
# pinning the host C standard here is enough. Same fix as tissot.
BUILD_CFLAGS:append = " -std=gnu17"
