DESCRIPTION = "Low level protocol implementation for binary protocol spoken by some Qualcomm modems"
HOMEPAGE = "http://www.freesmartphone.org"
AUTHOR = "Simon Busch <morphis@gravedo.de>"
SECTION = "console/network"
LICENSE = "GPLv2"
LIC_FILES_CHKSUM = "file://COPYING;md5=59530bdf33659b29e73d4adb9f9f6552"
INC_PR = "r4"
PV = "Please override!"

SRCREV = "811063659a32f329e8d00be0e758d7aad73707b5"
SRC_URI = "${FREESMARTPHONE_GIT}/msmcomm.git;protocol=git;branch=master"

