# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "furilabs-layer"
BBFILE_PATTERN_furilabs-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_furilabs-layer = "7"

LAYERDEPENDS_furilabs-layer = "core openembedded-layer android-layer"

LAYERSERIES_COMPAT_furilabs-layer = "wrynose"
