# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "minimal-layer"
BBFILE_PATTERN_minimal-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_minimal-layer = "7"

LAYERDEPENDS_minimal-layer = "core openembedded-layer android-layer"

LAYERSERIES_COMPAT_minimal-layer = "wrynose"
