#!/bin/sh
if [ -e /persist/wifi/.macaddr ] ; then
	echo "File /persist/wifi/.macaddr already exists"
	exit 1
fi

if [ ! -d /persist/wifi ] ; then
	mkdir -p /persist/wifi
fi

wifi_mac="`ifconfig wlan0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | sed -e 's:\:::g'`"
echo $wifi_mac > /persist/wifi/.macaddr
