# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "zinwa-layer"
BBFILE_PATTERN_zinwa-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_zinwa-layer = "7"

LAYERDEPENDS_zinwa-layer = "core openembedded-layer android-layer"

LAYERSERIES_COMPAT_zinwa-layer = "wrynose"
