#!/bin/sh

# Make sure the ubuntu_chroot init service does not get started
sed -i '/ubuntu_chroot init$/,+2d' $LXC_ROOTFS_PATH/init.rc

# Remove some services we don't want to have running inside the container
sed -i '/^service adbd/,+4d' $LXC_ROOTFS_PATH/init.rc
sed -i $LXC_ROOTFS_PATH/init.rc \
	-e 's|\(/system/bin/surfaceflinger\)|\1.disabled|' \
	-e 's|\(/system/bin/ubuntuappmanager\)|\1.disabled|' \
	-e 's|\(/sbin/upstart-property-watcher\)|\1.disabled|' \
	-e 's|\(/system/bin/sensorservice\)|\1.disabled|' \
	-e 's|\(/system/bin/mediaserver\)|\1.disabled|' \
	-e 's|\(/system/bin/servicemanager\)|\1.disabled|'
