#!/bin/sh

# (c) 2013 Canonical LTD.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the the GNU General Public License version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the applicable version of the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

pid=$(lxc-info -n android|grep ^pid|sed 's/^pid: .* //')
cmd=sh

PATH="/system/bin:/vendor/bin:$PATH"
LD_LIBRARY_PATH=/vendor/lib:/system/lib
ANDROID_CACHE=/cache
ANDROID_DATA=/data
ANDROID_ROOT=/system
ANDROID_ASSETS=/system/app
EXTERNAL_STORAGE=/mnt/sdcard
LOOP_MOUNTPOINT=/mnt/obb
ASEC_MOUNTPOINT=/mnt/asec
SHLVL=1
MKSH=/system/bin/sh

[ -n "$1" ] && cmd=$1 shift

chroot /proc/$pid/root/ $cmd "$@"
