# we need new headers for libc, now OLDEST_KERNEL_linux-gnueabi = "2.6.24"
# and 2.6.31 for fsodeviced
OLDEST_KERNEL = "2.6.24"

PREFERRED_VERSION_libnl = "3%"

PREFERRED_VERSION_frameworkd = "0.10.99+git%"
PREFERRED_VERSION_frameworkd-config = "0.10.99+git%"
PREFERRED_VERSION_fsoaudiod = "0.12.99+git%"
PREFERRED_VERSION_fsodatad = "0.12.99+git%"
PREFERRED_VERSION_fsodeviced-modules = "0.12.99"
PREFERRED_VERSION_fsodeviced = "0.12.99+git%"
PREFERRED_VERSION_fsogsmd-modules = "0.12.99"
PREFERRED_VERSION_fsogsmd = "0.12.99+git%"
PREFERRED_VERSION_fsonetworkd = "0.12.99+git%"
PREFERRED_VERSION_fsosystemd = "0.12.99+git%"
PREFERRED_VERSION_fsotdld = "0.12.99+git%"
PREFERRED_VERSION_fsousaged = "0.12.99+git%"
PREFERRED_VERSION_libfsoframework = "0.12.99+git%"
