#! /bin/sh
#
# fsosystemd -- This shell script starts and stops the FSO2 system subsystem daemon.
#
# chkconfig: 345 90 20
# description: fsosystemd is the freesmartphone.org FSO2 system daemon
# processname: fsosystemd

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=fsosystemd

[ -f /etc/default/rcS ] && . /etc/default/rcS

case "$1" in
    start)
        echo -n "Starting fsosystemd: "
        start-stop-daemon --start --pidfile /var/run/${NAME}.pid --make-pidfile --background -x /usr/sbin/fsosystemd
        if [ $? = 0 ]; then
            echo "(ok)"
        else
            echo "(failed)"
        fi
        ;;
    stop)
        echo -n "Stopping fsosystemd: "
        start-stop-daemon --stop --pidfile /var/run/${NAME}.pid --oknodo
        rm -f /var/run/${NAME}.pid
        echo "(done)"
        ;;
    restart|force-reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/fsosystemd {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

exit 0
