CFLAGS_append_mido = " -DQTI_BSP -DQCOM_HARDWARE"
CXXFLAGS_append_mido = " -DQTI_BSP -DQCOM_HARDWARE"

CFLAGS_append_tissot = " -DQTI_BSP -DQCOM_HARDWARE"
CXXFLAGS_append_tissot = " -DQTI_BSP -DQCOM_HARDWARE"
